---
- name: Install pip3
  ansible.builtin.package:
    name: python3-pip
    state: present

- name: Install PyMySQL dependency
  ansible.builtin.pip:
    name: PyMySQL
    executable: pip3

- name: Set python interpreter to python3
  ansible.builtin.set_fact:
    ansible_python_interpreter: /usr/bin/python3

- name: Install MySQL server
  ansible.builtin.yum:
    name: mysql-server
    state: present

- name: Start and enable MySQL service
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: true

#- name: Remove anonymous users
#  community.mysql.mysql_user:
#    name: ''
#    host_all: true
#    state: absent
#    login_user: root
#    login_password: "{{ mysql_root_password }}"

- name: Disable remote root login
  community.mysql.mysql_user:
    name: root
    host: '%'
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Remove test database
  community.mysql.mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"
